# 80MHz on channel 36 (non-DFS, so no CAC delay at startup)
channel=36
country_code=US
driver=nl80211
hw_mode=a
ieee80211d=1
ieee80211h=1
ieee80211n=1
ht_capab=[LDPC][HT40+][GF][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935]
require_ht=0
ieee80211ac=1
vht_capab=[MAX-MPDU-11454][VHT160][RXLDPC][SHORT-GI-80][SHORT-GI-160][TX-STBC-2BY1][RX-STBC-1][SU-BEAMFORMER][SU-BEAMFORMEE][MU-BEAMFORMER][MU-BEAMFORMEE][MAX-A-MPDU-LEN-EXP7][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN]
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42
ieee80211ax=1
he_oper_chwidth=1
he_oper_centr_freq_seg0_idx=42
he_su_beamformer=1
he_su_beamformee=1
noscan=0

interface=wlan1
ap_isolate=0
auth_algs=1
ctrl_interface=/run/hostapd
ctrl_interface_group=0
ieee80211w=1
ignore_broadcast_ssid=0
logger_syslog=-1
logger_syslog_level=2
macaddr_acl=0
rsn_pairwise=CCMP
sae_require_mfp=1
ssid=foobar-5g
utf8_ssid=1
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-PSK-SHA256
wpa_pairwise=CCMP
sae_password=foobarbaz
wpa_passphrase=foobarbaz
